version: '3.3'

name: ssd_ha

services:
  db:
    build: ./db
    restart: unless-stopped
    container_name: ssd_mysql
    hostname: ssd_mysql

    environment:
      MYSQL_DATABASE: 'ssd'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ssd_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'abcd1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'abcd1234'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      #prve cislo je externy port, kde je Mysql
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      #cislo portu mysql z externeho prostredia
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysqlData:/var/lib/mysql    # miesto na ulozenie DB
  php:
    build: ./php
    restart: unless-stopped
    depends_on:
      - db
    container_name: ssd_php
    
    environment:
      - EDITOR=vim
    volumes:
      - ./phpScripts:/phpScripts:ro
      #kde su ulozene subory z SSD a ich mapovanie do kontajnera
      - ./SSDfiles:/SSD
volumes:
  my-db:

networks:
  default:
    name: ssd-net